name: doc_scanner_sdk_example
description: Example app for doc_scanner_sdk
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.38.4'

dependencies:
  flutter:
    sdk: flutter
  doc_scanner_sdk:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
